apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-external
  name: nfs-external
  namespace: kubeflow-test-infra
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
