apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
  namespace: kubeflow-test-infra
spec:
  capacity:
    storage: 5Gi
  # VolumeMode is only 1.9 & later
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-external
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: 10.142.0.6