apiVersion: 0.0.1
kind: ksonnet.io/app
name: my-kubeflow
libraries:
  core:
    gitVersion:
      commitSha: b43febd44d7a2e694f178bdd0d884cc2600f3ad8
      refSpec: master
    name: core
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: b43febd44d7a2e694f178bdd0d884cc2600f3ad8
      refSpec: master
    name: tf-serving
    registry: kubeflow
registries:
  incubator:
    gitVersion:
      commitSha: ea3408d44c2d8ea4d321364e5533d5c60e74bce0
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
